INSERT INTO tb_ativo (
  id, company_id, ATIVO_EMPRESA, ATIVO_CODPE, ATIVO_DESCRITIVO_OS, ATIVO_STATUS, ATIVO_COORDENACAO, ATIVO_EQUIPE,
  ATIVO_MONITORADOS, ATIVO_SIGLA, ATIVO_CICLO, ATIVO_CONTADOR, CONTADOR_CICLO, ATIVO_TOLERANCIA, ATIVO_CLASSE,
  ATIVO_GRUPO, ATIVO_OEA, ATIVO_TMM, ATIVO_ULTIMA_MANUT
) VALUES (
  'ativo_tec_001', 'cmp_tecrail', 'TecRail', 'ATV-001', 'Ativo teste', 'ativo', 'PCM', 'EQUIPE1',
  'Sim', 'SUB1', 'Mensal', 1, 'CIC-1', '5', 'Classe A', 'Grupo 1', 'OEA-1', 'TMM-1', datetime('now')
);
