# -*- coding: utf-8 -*-
from pathlib import Path
path = Path('frontend/src/pages/ConfiguracaoPerfilAcesso.tsx')
text = path.read_text(encoding='utf-8')
old = "          <div style={{ display: 'grid', gap: 6 }}>\n            <label style={fieldLabelStyle}>Coordenação *</label>\n            <select\n              value={formState.Coordenação}\n              onChange={event => handleFormChange('Coordenação', event.target.value)}\n              style={{ padding: '10px 12px', borderRadius: 10, border: '1px solid #e2e8f0' }}\n            >\n              <option value=\"\">\n                {estruturaCoordOptions.length\n                  ? 'Selecione a coordenação'\n                  : 'Carregando coordenações...'}\n              </option>\n              {estruturaCoordOptions.map(coord => (\n                <option key={coord} value={coord}>\n                  {coord}\n                </option>\n              ))}\n            </select>\n          </div>\n"
new = "          <div style={{ display: 'grid', gap: 6 }}>\n            <label style={fieldLabelStyle}>Coordenação *</label>\n            <input\n              value={formState.Coordenação}\n              onChange={event => {\n                handleFormChange('Coordenação', event.target.value)\n                handleFormChange('equipeAtual', '')\n              }}\n              placeholder={\n                estruturaCoordOptions.length\n                  ? 'Digite ou escolha uma coordenação'\n                  : 'Digite uma coordenação para criar'\n              }\n              list={estruturaCoordOptions.length ? 'coord-options' : undefined}\n              style={{ padding: '10px 12px', borderRadius: 10, border: '1px solid #e2e8f0' }}\n            />\n            {estruturaCoordOptions.length > 0 && (\n              <datalist id=\"coord-options\">\n                {estruturaCoordOptions.map(coord => (\n                  <option key={coord} value={coord} />\n                ))}\n              </datalist>\n            )}\n          </div>\n"
if old not in text:
    raise RuntimeError('old snippet not found')
path.write_text(text.replace(old, new, 1), encoding='utf-8')
